#!/bin/bash 

echo "=== Menu Principal YAGO==="
echo "1. Choix utilisateur" 
echo "2. Choix ordinateur client" 
echo "3. Quitter" 
read -p "Sélectionnez une option (1, 2 ou 3) : " choix

case $choix in 
1) 
echo "Vous avez choisi : Choix utilisateur" 
if verification_password; 
then 
echo "Accès accordé à l'utilisateur." 
# Ici, ajouter les actions pour l'utilisateur. 
else 
echo "Accès refusé." fi 
;; 
2) 
echo "Vous avez choisi : Choix ordinateur client" 
if verification_password; 
then 
echo "Accès accordé à l'ordinateur client." 
# Ici, ajouter les actions pour l'ordinateur client. 
else 
echo "Accès refusé." 
fi ;; 
3)
 echo "Vous avez choisi de quitter le programme." 
exit 0 ;; *) 
echo "Option invalide. Veuillez sélectionner 1, 2 ou 3." 
;; 
esac
 
done
 
# Mot de passe défini pour l'authentification 
PASSWORD="monMotDePasse" 
# Fonction pour vérifier le mot de passe () 
{ read -sp "Entrez le mot de passe : " input_password 
echo if [ "$input_password" == "$PASSWORD" ]; 
then 
echo "Authentification réussie." 
EXIT 0 
